version: '3'

services:
  db:
    image: mariadb:10.3.2
    volumes:
      - .data/db:/var/lib/mysql
    restart: always
    ports:
      - 3306
    container_name: rw_stories_db
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    build: .
    ports:
      - "80:80"
    restart: always
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./www/wp-content:/var/www/html/wp-content
      - ./src:/var/www/html/wp-content/themes/resourcewatch
    container_name: rw_stories
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_PORT: 3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
